[package]
name = "daphne"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "13.0.0"
terminal_size = "0.3.0"

[[bin]]
name = "daphne"
path = "src/daphne.rs"
